### ISSUE TITLE
Help: 

### ISSUE THREAD

**Issue by autisticism** [Friends-of-Monika/mas-selfharm#30]
### What do you need our help with?

Hello! How do I download this submod? I've looked around and I can't seem to find a download button. Thank you!

**Comment by dreamscached** [comment]
Hi, go [here](https://github.com/Friends-of-Monika/mas-selfharm/releases/tag/2.0.1) and scroll right to the bottom, you'll see .zip files. **Please read instructions on the same page!**

**Comment by autisticism** [comment]
Thank you :)
