### ISSUE TITLE
The gift feature isn't working

### ISSUE THREAD

**Issue by ghost** [Friends-of-Monika/mas-selfharm#33]
### What do you need our help with?

I tried to give Moonika a semicolon heart hoodie, and she couldn't read the file. Help please!

**Comment by dreamscached** [comment]
Make sure you have installed the spritepack properly. Anything in spj.log to look at, errors etc?

**Comment by ghost** [comment]
I did download an earlier version of the spritepack, maybe that's the problem.

**Comment by dreamscached** [comment]
What do you mean by earlier version?

**Comment by ghost** [comment]
I went to the second release.

**Comment by ghost** [comment]
So, all I did was put the file in the characters folder. Was I supposed to manually add assets into the game, or was installing the submod enough?

**Comment by dreamscached** [comment]
You should add spritepacks yourself, they don't come bundled, they're separate.

**Comment by ghost** [comment]
Oh okay. Thanks!
