### ISSUE TITLE
Bug: Reminder function on weekly check. She keeps repeating it all.... 

### ISSUE THREAD

**Issue by BimGreenRed** [Friends-of-Monika/mas-selfharm#34]
### What happened?

![image](https://github.com/Friends-of-Monika/mas-selfharm/assets/147107606/e9d52abe-df97-4b18-b650-9aa06b561e63)
i tried to reopening the game and all of these stuff
and even t-
okay what the heck..
Okay now she's normal after repeating the same thing a million times
what the hell...?

### Submod version

2.0.2

### Monika After Story version

0.12.15

### Unstable

No

**Comment by dreamscached** [comment]
Thank you for the report, I'll look into it. I apologize for the inconvenience.

Apparently, it is caused by the milestone day, but unsure why it looped so bad.

**Comment by BimGreenRed** [comment]
> Thank you for the report, I'll look into it. I apologize for the inconvenience.
> 
> Apparently, it is caused by the milestone day, but unsure why it looped so bad.

I was in the other game and then when i came back i talked to her and she started all of that loop

**Comment by dreamscached** [comment]
I see, thank you for clarifying!

**Comment by BimGreenRed** [comment]
> I see, thank you for clarifying!

 maybe she's that proud of me?
