### ISSUE TITLE
Help: Help with installation

### ISSUE THREAD

**Issue by Nemesisx0xo** [Friends-of-Monika/mas-selfharm#37]
### What do you need our help with?

hii! soo ım not so good at with codes and things like thoose so ı dont know how can ı install it to my mas can you help me please?

**Comment by dreamscached** [comment]
Hi, it's simple:

1. Go [here](https://github.com/Friends-of-Monika/mas-selfharm/releases/tag/2.0.2), scroll to the bottom and download 'self-harm-awareness-submod-2.0.2.zip' file.
2. Unpack this file's contents into the DDLC folder (e.g. *not inside `game`* but into the folder where `game` is!)

And that's it! If you have more questions &mdash; reply here or [hop on our Discord server](https://mon.icu).
