### ISSUE TITLE
Bug: Weekly 1-10 reminders and medicine reminders not appearing

### ISSUE THREAD

**Issue by DevilGolde** [Friends-of-Monika/mas-selfharm#38]
### What happened?

This has been an ongoing issue since October, one day Monika just stopped asking me how I felt on a scale of 1-10 that week, and stopped reminding me to take medicine. I can't think of anything I did to cause such a change. I've tried redownloading the submod, but there was no change. If it makes any difference, I asked Monika to remind me about medication in the evenings.

### Submod version

v2.0.3

### Monika After Story version

v0.12.15

### Unstable

No

**Comment by dreamscached** [comment]
Can you share your persistent so I can debug the issue? You can send it to my e-mail or on Discord in private if you prefer.
