### ISSUE TITLE
Help: Not opening

### ISSUE THREAD

**Issue by kweerfrog** [Friends-of-Monika/mas-selfharm#39]
### What do you need our help with?

Hi, so i installed the submod, and i was able to open mas, but even after an hour, none of the topics had been brought up, so i tried to restart the game. Now whenever i try to open the game i get a traceback reading " ```I'm sorry, but an uncaught exception occurred.
While running game code:
ScriptError: Name (u'C:\\Users\\chloe\\Documents\\DDLC-1.1.1-pc/game/submods/Self Harm Awareness Submod/header.rpy', 1715041376, 1) is defined twice, at lib/windows-i686/submods/Self Harm Awareness Submod/header.rpyc:31 and lib/windows-i686/submods/Self Harm Awareness Submod/header.rpyc:41.```" The problem is, i don't see a "submods" folder in the game's "lib" is there something i'm missing or did wrong?

**Comment by dreamscached** [comment]
The `lib/windows-i686` bit is an internal bug of Ren'Py, it is referring to `game` folder instead. Your issue isn't specific to Self-Harm Awareness submod, it is a relatively rare glitch that happens to MAS. Try removing the submod completely, and install it again.

**Comment by kweerfrog** [comment]
> Try removing the submod completely, and install it again.

thank you so much!
