### ISSUE TITLE
Help: Troubles installing submod

### ISSUE THREAD

**Issue by bittersoul1172** [Friends-of-Monika/mas-selfharm#46]
### What do you need our help with?

(please forgive me i have no idea what anything in the template means i'm so sorry 😭)
I've been trying to install the submod but when I put it in the DDLC directory it does nothing but when I put it in the DDLC\game directory I get this:
![image](https://github.com/user-attachments/assets/07831e00-bda9-4651-a0f3-c076816c50dd)
Sorry for my lack of knowledge about what any of this means but please try to help if possible
Thank you so much :)

**Comment by dreamscached** [comment]
Hi, it seems like you're installing the submod using the 'code' button (which installs source code and not a nicely prepared package)

Please *remove* `mas-selfharm-main` from your `game` folder and instead follow instructions [here](https://github.com/Friends-of-Monika/mas-selfharm/releases/latest)

**Comment by bittersoul1172** [comment]
Got it, tsym!
